spring.application.name=momo-payment

momo.partner-code=MOMOLRJZ20181206
momo.return-url=http://localhost:3000/
momo.end-point=https://test-payment.momo.vn/v2/gateway/api
momo.ipn-url=http://localhost:8080/api/momo/ipn-handler
momo.access-key=mTCKt9W3eU1m39TW
momo.secret-key=SetA5RDnLHvt51AULf51DyauxUo3kDU6
momo.request-type=captureWallet
